backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
  - name: "services"
    label: "Usługi"
    files:
      - file: "index.html"
        label: "Strona Główna"
        fields:
          - {label: "Treść Usług", name: "services", widget: "markdown"}
          - {label: "Treść Portfolio", name: "portfolio", widget: "markdown"}